### ISSUE TITLE
SD Phase 3 Full Stack- Courses

### ISSUE THREAD

**Issue by tonantr** [learn-co-curriculum/python-p3-welcome-to-phase-3#1]
### Canvas Link

https://my.learn.co/courses/653

### Concern

Hi there,

I am wondering why I cannot access the courses in Phase 3.

Thanks

**Comment by lizbur10** [comment]
@lberge17

**Comment by lberge17** [comment]
Hi @tonantr, can you reach out on Piazza to let us know what you're seeing? Our instructional team can help you there with Canvas issues. Issues added to GitHub are for curriculum issues - such as typos or bugs in lessons. Any Canvas issues can be send to us in Piazza.
